In [1]:
import numpy as np
import pandas as pd

# Data Reading

In [2]:
df_raw = pd.read_csv("DataCoSupplyChainDataset.csv",  encoding="latin1")

# Data Understanding

In [3]:
df_raw.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [4]:
df_raw.sample(7)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
81668,DEBIT,5,2,76.550003,263.959992,Late delivery,1,17,Cleats,Campbell,...,80906.0,365,17,NaN,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,59.990002,0,7/28/2016 11:59,Second Class
4118,DEBIT,4,4,91.339996,260.980011,Shipping on time,0,43,Camping & Hiking,West Lafayette,...,NaN,957,43,NaN,http://images.acmesports.sports/Diamondback+Wo...,Diamondback Women's Serene Classic Comfort Bi,299.980011,0,2/13/2016 18:00,Standard Class
143479,CASH,2,1,84.570000,179.929993,Late delivery,1,46,Indoor/Outdoor Games,Fresno,...,NaN,1014,46,NaN,http://images.acmesports.sports/O%27Brien+Men%...,O'Brien Men's Neoprene Life Vest,49.980000,0,9/18/2015 15:45,First Class
27172,DEBIT,2,1,152.229996,434.959992,Late delivery,1,9,Cardio Equipment,Caguas,...,NaN,191,9,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,5/13/2015 14:10,First Class
19764,PAYMENT,1,0,-56.689999,84.989998,Late delivery,1,9,Cardio Equipment,Miami,...,NaN,191,9,NaN,http://images.acmesports.sports/Nike+Men%27s+F...,Nike Men's Free 5.0+ Running Shoe,99.989998,0,1/15/2017 8:19,Same Day
169454,TRANSFER,5,2,76.720001,278.980011,Late delivery,1,43,Camping & Hiking,Springfield,...,NaN,957,43,NaN,http://images.acmesports.sports/Diamondback+Wo...,Diamondback Women's Serene Classic Comfort Bi,299.980011,0,1/8/2016 12:58,Second Class
101772,DEBIT,3,4,49.400002,189.990005,Advance shipping,0,48,Water Sports,Caguas,...,NaN,1073,48,NaN,http://images.acmesports.sports/Pelican+Sunstr...,Pelican Sunstream 100 Kayak,199.990005,0,12/30/2015 1:35,Standard Class

In [5]:
df_raw.shape

(180519, 53)

In [6]:
df_raw.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [7]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [8]:
df_raw.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

## Data to Keep

In [9]:
columns_to_keep = ["Days for shipping (real)", "Days for shipment (scheduled)", "Benefit per order", "Delivery Status",
                   "Late_delivery_risk", "Category Name", "Customer City", "Customer Country",
                   "Customer Segment", "Latitude", "Longitude", "Market",
                   "Order City", "Order Country", "order date (DateOrders)", "Order Id",
                   "Order Item Quantity", "Sales", "Order Region", "Order State",
                   "Order Status", "Product Name", "shipping date (DateOrders)", "Shipping Mode"
                   ]

df = df_raw[columns_to_keep]

In [10]:
df.sample(10)

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Segment,Latitude,...,order date (DateOrders),Order Id,Order Item Quantity,Sales,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode
105690,3,4,81.570000,Advance shipping,0,Indoor/Outdoor Games,Elyria,EE. UU.,Corporate,41.361259,...,5/20/2017 0:53,59602,4,199.919998,Central America,Francisco Morazán,COMPLETE,O'Brien Men's Neoprene Life Vest,5/23/2017 0:53,Standard Class
155320,2,4,27.709999,Advance shipping,0,Women's Apparel,Caguas,Puerto Rico,Consumer,18.219736,...,1/29/2017 1:54,52001,4,200.000000,Central America,Puebla,PENDING_PAYMENT,Nike Men's Dri-FIT Victory Golf Polo,1/31/2017 1:54,Standard Class
25628,2,1,76.489998,Late delivery,1,Cleats,Las Vegas,EE. UU.,Corporate,36.113194,...,3/18/2017 15:51,55329,4,239.960007,South America,Distrito Federal,COMPLETE,Perfect Fitness Perfect Rip Deck,3/20/2017 15:51,First Class
131428,2,1,105.559998,Late delivery,1,Indoor/Outdoor Games,Elgin,EE. UU.,Consumer,41.976704,...,3/5/2016 23:02,29455,5,249.899994,Southeast Asia,Capital Nacional,PENDING,O'Brien Men's Neoprene Life Vest,3/7/2016 23:02,First Class
85829,3,4,88.550003,Advance shipping,0,Camping & Hiking,Oxnard,EE. UU.,Corporate,34.190392,...,5/13/2015 1:13,9047,1,299.980011,South America,Minas Gerais,PENDING,Diamondback Women's Serene Classic Comfort Bi,5/16/2015 1:13,Standard Class
116950,2,1,34.410000,Late delivery,1,Hunting & Shooting,Marrero,EE. UU.,Consumer,29.763435,...,9/18/2016 6:07,42902,5,149.949997,East Africa,Maputo,PROCESSING,ENO Atlas Hammock Straps,9/20/2016 6:07,First Class
7784,5,2,8.450000,Late delivery,1,Women's Apparel,Caguas,Puerto Rico,Corporate,18.219275,...,8/1/2017 11:49,64634,2,100.000000,Western Europe,Brandenburgo,CLOSED,Nike Men's Dri-FIT Victory Golf Polo,8/6/2017 11:49,Second Class
57022,4,4,-9.570000,Shipping on time,0,Shop By Sport,Caguas,Puerto Rico,Consumer,18.282988,...,10/2/2016 15:34,43888,4,159.960007,West Africa,Osun,COMPLETE,Under Armour Girls' Toddler Spine Surge Runni,10/6/2016 15:34,Standard Class
4770,5,4,-162.929993,Late delivery,1,Cleats,North Tonawanda,EE. UU.,Consumer,43.029102,...,2/5/2017 18:53,52529,4,239.960007,Central America,Guatemala,PENDING,Perfect Fitness Perfect Rip Deck,2/10/2017 18:53,Standard Class
46287,3,4,13.580000,Advance shipping,0,Women's Apparel,Washington,EE. UU.,Corporate,38.885834,...,1/9/2017 23:18,50692,1,50.000000,West Asia,Doha,PENDING_PAYMENT,Nike Men's Dri-FIT Victory Golf Polo,1/12/2017 23:18,Standard Class

In [11]:
df.shape

(180519, 24)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 24 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Days for shipping (real)       180519 non-null  int64
 1   Days for shipment (scheduled)  180519 non-null  int64
 2   Benefit per order              180519 non-null  float64
 3   Delivery Status                180519 non-null  object
 4   Late_delivery_risk             180519 non-null  int64
 5   Category Name                  180519 non-null  object
 6   Customer City                  180519 non-null  object
 7   Customer Country               180519 non-null  object
 8   Customer Segment               180519 non-null  object
 9   Latitude                       180519 non-null  float64
 10  Longitude                      180519 non-null  float64
 11  Market                         180519 non-null  object
 12  Order City                     180519 non-null  object
 13  Order Country                  180519 non-null  object
 14  order date (DateOrders)        180519 non-null  object
 15  Order Id                       180519 non-null  int64
 16  Order Item Quantity            180519 non-null  int64
 17  Sales                          180519 non-null  float64
 18  Order Region                   180519 non-null  object
 19  Order State                    180519 non-null  object
 20  Order Status                   180519 non-null  object
 21  Product Name                   180519 non-null  object
 22  shipping date (DateOrders)     180519 non-null  object
 23  Shipping Mode                  180519 non-null  object
dtypes: float64(4), int64(5), object(15)
memory usage: 33.1+ MB

# Data Cleaning

## Missing Values

In [13]:
df.isna().sum()

Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Delivery Status                  0
Late_delivery_risk               0
Category Name                    0
Customer City                    0
Customer Country                 0
Customer Segment                 0
Latitude                         0
Longitude                        0
Market                           0
Order City                       0
Order Country                    0
order date (DateOrders)          0
Order Id                         0
Order Item Quantity              0
Sales                            0
Order Region                     0
Order State                      0
Order Status                     0
Product Name                     0
shipping date (DateOrders)       0
Shipping Mode                    0
dtype: int64

## Duplicates

In [14]:
df.duplicated().sum()

np.int64(8)

In [15]:
df[df.duplicated()]

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Segment,Latitude,...,order date (DateOrders),Order Id,Order Item Quantity,Sales,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode
24916,2,1,0.000000,Late delivery,1,Fishing,Longmont,EE. UU.,Corporate,40.190121,...,2/7/2015 21:08,2596,1,399.980011,Central America,San Salvador,COMPLETE,Field & Stream Sportsman 16 Gun Fire Safe,2/9/2015 21:08,First Class
75902,3,4,0.000000,Advance shipping,0,Water Sports,Caguas,Puerto Rico,Consumer,18.274555,...,3/13/2015 9:32,4892,1,199.990005,Central America,Sinaloa,PENDING_PAYMENT,Pelican Sunstream 100 Kayak,3/16/2015 9:32,Standard Class
79066,4,4,72.000000,Shipping on time,0,Water Sports,Troy,EE. UU.,Consumer,42.580460,...,6/9/2016 9:36,35993,1,199.990005,US Center,Michigan,COMPLETE,Pelican Sunstream 100 Kayak,6/13/2016 9:36,Standard Class
119590,3,2,0.000000,Late delivery,1,Cleats,Chicago,EE. UU.,Consumer,41.895512,...,4/13/2015 15:16,7032,4,239.960007,Caribbean,Isla de la Juventud,PENDING,Perfect Fitness Perfect Rip Deck,4/16/2015 15:16,Second Class
122641,4,2,51.480000,Shipping canceled,0,Men's Footwear,Caguas,Puerto Rico,Corporate,18.295212,...,2/21/2017 2:24,53578,1,129.990005,Central America,Chihuahua,SUSPECTED_FRAUD,Nike Men's CJ Elite 2 TD Football Cleat,2/25/2017 2:24,Second Class
128184,4,4,18.000000,Shipping on time,0,Cleats,Annandale,EE. UU.,Consumer,38.825516,...,8/25/2016 0:54,41243,2,119.980003,East of USA,Pensilvania,COMPLETE,Perfect Fitness Perfect Rip Deck,8/29/2016 0:54,Standard Class
157490,0,0,22.959999,Shipping canceled,0,Cleats,Caguas,Puerto Rico,Consumer,18.205091,...,7/4/2017 0:17,62683,5,299.950012,Western Europe,Países del Loira,SUSPECTED_FRAUD,Perfect Fitness Perfect Rip Deck,7/4/2017 12:17,Same Day
172591,2,1,8.660000,Late delivery,1,Shop By Sport,Caguas,Puerto Rico,Consumer,18.203648,...,12/8/2015 20:01,23418,3,119.970001,South Asia,Rajastán,CLOSED,Under Armour Girls' Toddler Spine Surge Runni,12/10/2015 20:01,First Class

In [16]:
df = df.drop_duplicates()
df

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,Customer Segment,Latitude,...,order date (DateOrders),Order Id,Order Item Quantity,Sales,Order Region,Order State,Order Status,Product Name,shipping date (DateOrders),Shipping Mode
0,3,4,91.250000,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Consumer,18.251453,...,1/31/2018 22:56,77202,1,327.750000,Southeast Asia,Java Occidental,COMPLETE,Smart watch,2/3/2018 22:56,Standard Class
1,5,4,-249.089996,Late delivery,1,Sporting Goods,Caguas,Puerto Rico,Consumer,18.279451,...,1/13/2018 12:27,75939,1,327.750000,South Asia,Rajastán,PENDING,Smart watch,1/18/2018 12:27,Standard Class
2,4,4,-247.779999,Shipping on time,0,Sporting Goods,San Jose,EE. UU.,Consumer,37.292233,...,1/13/2018 12:06,75938,1,327.750000,South Asia,Rajastán,CLOSED,Smart watch,1/17/2018 12:06,Standard Class
3,3,4,22.860001,Advance shipping,0,Sporting Goods,Los Angeles,EE. UU.,Home Office,34.125946,...,1/13/2018 11:45,75937,1,327.750000,Oceania,Queensland,COMPLETE,Smart watch,1/16/2018 11:45,Standard Class
4,2,4,134.210007,Advance shipping,0,Sporting Goods,Caguas,Puerto Rico,Corporate,18.253769,...,1/13/2018 11:24,75936,1,327.750000,Oceania,Queensland,PENDING_PAYMENT,Smart watch,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,4,4,40.000000,Shipping on time,0,Fishing,Brooklyn,EE. UU.,Home Office,40.640930,...,1/16/2016 3:40,26043,1,399.980011,Eastern Asia,Shanghái,CLOSED,Field & Stream Sportsman 16 Gun Fire Safe,1/20/2016 3:40,Standard Class
180515,3,2,-613.770019,Late delivery,1,Fishing,Bakersfield,EE. UU.,Corporate,35.362545,...,1/16/2016 1:34,26037,1,399.980011,Eastern Asia,Osaka,COMPLETE,Field & Stream Sportsman 16 Gun Fire Safe,1/19/2016 1:34,Second Class
180516,5,4,141.110001,Late delivery,1,Fishing,Bristol,EE. UU.,Corporate,41.629959,...,1/15/2016 21:00,26024,1,399.980011,Oceania,Australia del Sur,PENDING,Field & Stream Sportsman 16 Gun Fire Safe,1/20/2016 21:00,Standard Class
180517,3,4,186.229996,Advance shipping,0,Fishing,Caguas,Puerto Rico,Consumer,18.213350,...,1/15/2016 20:18,26022,1,399.980011,Oceania,Australia del Sur,PENDING_PAYMENT,Field & Stream Sportsman 16 Gun Fire Safe,1/18/2016 20:18,Standard Class
180518,4,4,168.949997,Shipping on time,0,Fishing,Caguas,Puerto Rico,Consumer,18.290380,...,1/15/2016 18:54,26018,1,399.980011,South Asia,Tamil Nadu,PENDING_PAYMENT,Field & Stream Sportsman 16 Gun Fire Safe,1/19/2016 18:54,Standard Class

## Unique Values

In [17]:
df.nunique()

Days for shipping (real)             7
Days for shipment (scheduled)        4
Benefit per order                21998
Delivery Status                      4
Late_delivery_risk                   2
Category Name                       50
Customer City                      563
Customer Country                     2
Customer Segment                     3
Latitude                         11250
Longitude                         4487
Market                               5
Order City                        3597
Order Country                      164
order date (DateOrders)          65752
Order Id                         65752
Order Item Quantity                  5
Sales                              193
Order Region                        23
Order State                       1089
Order Status                         9
Product Name                       118
shipping date (DateOrders)       63701
Shipping Mode                        4
dtype: int64

In [18]:
df["Customer Country"].value_counts()

Customer Country
EE. UU.        111142
Puerto Rico     69369
Name: count, dtype: int64

In [19]:
df["Market"].value_counts()

Market
LATAM           51590
Europe          50251
Pacific Asia    41259
USCA            25797
Africa          11614
Name: count, dtype: int64

## Data Types

In [20]:
df.dtypes

Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Segment                  object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
order date (DateOrders)           object
Order Id                           int64
Order Item Quantity                int64
Sales                            float64
Order Region                      object
Order State                       object
Order Status                      object
Product Name                      object
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [21]:
df["order date (DateOrders)"] = pd.to_datetime(df["order date (DateOrders)"])
df["shipping date (DateOrders)"] = pd.to_datetime(df["shipping date (DateOrders)"])
df.dtypes

Days for shipping (real)                  int64
Days for shipment (scheduled)             int64
Benefit per order                       float64
Delivery Status                          object
Late_delivery_risk                        int64
Category Name                            object
Customer City                            object
Customer Country                         object
Customer Segment                         object
Latitude                                float64
Longitude                               float64
Market                                   object
Order City                               object
Order Country                            object
order date (DateOrders)          datetime64[ns]
Order Id                                  int64
Order Item Quantity                       int64
Sales                                   float64
Order Region                             object
Order State                              object
Order Status                             object
Product Name                             object
shipping date (DateOrders)       datetime64[ns]
Shipping Mode                            object
dtype: object

## Rename Columns

In [22]:
df = df.rename(columns=
    {"Days for shipping (real)": "actual_shipping_days",
    "Days for shipment (scheduled)": "scheduled_shipping_days",
    "Benefit per order": "benefit_per_order",
    "Delivery Status": "delivery_status",
    "Category Name": "category_name",
    "Customer City": "customer_city",
    "Customer Country": "customer_country",
    "Customer Segment": "customer_segment",
    "Latitude": "latitude",
    "Longitude": "longitude",
    "Market": "market",
    "Order City": "order_city",
    "Order Country": "order_country",
    "order date (DateOrders)": "order_date",
    "Order Id": "order_id",
    "Order Item Quantity": "order_item_quantity",
    "Sales": "sales",
    "Order Region": "order_region",
    "Order State": "order_state",
    "Order Status": "order_status",
    "Product Name": "product_name",
    "shipping date (DateOrders)": "shipping_date",
    "Shipping Mode": "shipping_mode",
    "Late_delivery_risk": "is_late",}
)

## Feature Engineering

### Delivery Delay

In [23]:
df["delivery_delay_days"]  = (df["actual_shipping_days"] - df["scheduled_shipping_days"])

### Date Features

In [24]:
df["order_year"] = df["order_date"].dt.year
df["order_month"] = df["order_date"].dt.month

### Delay Categories

In [25]:
def classify_delay(days):
    if days <= 0:
        return "On Time"
    elif days <= 2:
        return "Slightly Late"
    else:
        return "Highly Delayed"

df["delay_category"] = df["delivery_delay_days"].apply(classify_delay)

In [26]:
df.sample(10)

,actual_shipping_days,scheduled_shipping_days,benefit_per_order,delivery_status,is_late,category_name,customer_city,customer_country,customer_segment,latitude,...,order_region,order_state,order_status,product_name,shipping_date,shipping_mode,delivery_delay_days,order_year,order_month,delay_category
45813,4,4,22.309999,Shipping on time,0,Women's Apparel,El Paso,EE. UU.,Corporate,31.771334,...,South America,Buenos Aires,PENDING_PAYMENT,Nike Men's Dri-FIT Victory Golf Polo,2015-02-15 13:25:00,Standard Class,0,2015,2,On Time
115600,4,4,85.559998,Shipping on time,0,Fishing,Marietta,EE. UU.,Corporate,34.072311,...,Western Europe,Auvernia-Ródano-Alpes,COMPLETE,Field & Stream Sportsman 16 Gun Fire Safe,2017-08-29 17:02:00,Standard Class,0,2017,8,On Time
106760,2,1,-329.670013,Late delivery,1,Indoor/Outdoor Games,Caguas,Puerto Rico,Corporate,18.203445,...,Central America,San Salvador,PENDING,O'Brien Men's Neoprene Life Vest,2017-03-30 08:08:00,First Class,1,2017,3,Slightly Late
54753,2,4,25.000000,Advance shipping,0,Water Sports,South El Monte,EE. UU.,Corporate,34.047291,...,Central America,Michoacán,PENDING_PAYMENT,Pelican Sunstream 100 Kayak,2017-05-24 22:36:00,Standard Class,-2,2017,5,On Time
126705,4,4,80.989998,Shipping on time,0,Camping & Hiking,Caguas,Puerto Rico,Consumer,18.254828,...,Northern Europe,Inglaterra,PENDING_PAYMENT,Diamondback Women's Serene Classic Comfort Bi,2015-07-04 16:12:00,Standard Class,0,2015,6,On Time
140393,4,2,13.950000,Late delivery,1,Men's Footwear,Vega Baja,Puerto Rico,Home Office,18.444847,...,Central America,Guatemala,CLOSED,Nike Men's CJ Elite 2 TD Football Cleat,2015-05-17 03:19:00,Second Class,2,2015,5,Slightly Late
54803,6,4,73.800003,Late delivery,1,Water Sports,Caguas,Puerto Rico,Corporate,18.287096,...,Central America,San Salvador,PENDING_PAYMENT,Pelican Sunstream 100 Kayak,2017-05-26 01:56:00,Standard Class,2,2017,5,Slightly Late
9074,4,4,38.400002,Shipping on time,0,Women's Apparel,Hempstead,EE. UU.,Corporate,40.662224,...,South America,São Paulo,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,2017-05-23 07:43:00,Standard Class,0,2017,5,On Time
97885,2,2,4.000000,Shipping on time,0,Women's Apparel,Denver,EE. UU.,Home Office,39.689751,...,South of USA,Georgia,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,2016-04-22 12:28:00,Second Class,0,2016,4,On Time
173021,6,2,-214.479996,Late delivery,1,Men's Footwear,Caguas,Puerto Rico,Consumer,18.247534,...,Eastern Asia,Henan,CLOSED,Nike Men's CJ Elite 2 TD Football Cleat,2015-11-17 11:49:00,Second Class,4,2015,11,Highly Delayed